### ISSUE TITLE
Nice ITCSS example

### ISSUE THREAD

**Issue by brunowego** [robaguilera/itcss-sass-starter#1]
I have a question, how you generate the structure of your README.md? Thanks

**Comment by robaguilera** [comment]
Whoa sorry man.  Didn't see this comment till right now.  Really sorry.  Not sure I understand.  I just used markdown to write it out.  You can go here to learn more about it: https://daringfireball.net/projects/markdown/syntax
Did that answer your question?  Again sorry for the way late response.

**Comment by brunowego** [comment]
I solve this using https://github.com/animade/frontend-md, thanks for your patience and sorry for the delay.
